### ISSUE TITLE
Filter: Fatal error (metamodels/bundle_all 1.0.1)

### ISSUE THREAD

**Issue by surelyfx** [MetaModels/bundle_all#3]
After confirming the filter always get this error:

Fatal error: Call to a member function searchFor() on a non-object in [...]

Never had the problem before and filter set up as usual.

**Comment by discordier** [comment]
What attribute is selected in your filter? What is your filter setup in general?

**Comment by surelyfx** [comment]
Thank you for your quick reply! The attribute is a multiple selection generated by another metamodel. The tpye of the filter is a multiple selection, but it's producing the same error using single selection.
![bildschirmfoto 2015-10-20 um 09 47 41](https://cloud.githubusercontent.com/assets/15209214/10601119/ab2d2562-770f-11e5-8c52-663d1e0668eb.png)

**Comment by discordier** [comment]
Somehow it is unable to instantiate the attribute (which is where the "searchFor" method is located in).
Could you provide the whole error message including stack trace? It is hard to pin point it without the details.

**Comment by surelyfx** [comment]
Hi there! Sorry for my late reply! Here's the whole error message:

Fatal error: Call to a member function searchFor() on a non-object in /var/www/pfeifertour/composer/vendor/metamodels/attribute_tags/src/MetaModels/Filter/Rules/FilterRuleTags.php on line 146

**Comment by xantippe** [comment]
use bundle_all 2.0.0 - filter works fine
