### ISSUE TITLE
Fatal error: Cannot use 'String' as class name

### ISSUE THREAD

**Issue by JLNNN** [MetaModels/bundle_all#6]
Hey,

I just got the following error:

```
Fatal error: Cannot use 'String' as class name as it is reserved in /var/www/system/modules/core/library/Contao/String.php on line 28
```

contao: 3.5.40
metamodels/bundle_all: 2.0.0
php: 7.2

Can you help me? Thanks in advance,
  Julian

**Comment by zonky2** [comment]
'String' is reserved name in PHP 7x - please update your MM (composer!) or change to Contao 4 and MM 2.1

**Comment by JLNNN** [comment]
@zonky2 can you please tell me which mm version to use if I'm unable to upgrade to Contao 4 & mm 2.1 at the moment?

**Comment by zonky2** [comment]
make a update with your package manager or composer update at console

it is also possible that the message comes through another extension - MM is PHP 7 ready for a long time

**Comment by JLNNN** [comment]
But 2.0.0 is the last release that's been made for Contao 3.5 or am I getting some things wrong?

https://github.com/MetaModels/bundle_all/releases

**Comment by zonky2** [comment]
bundle_all calls other bundles which in turn call the actual repositories - they must be up-to-date!

**Comment by JLNNN** [comment]
So I have to check every (recursively) linked package and update them manually to the latest 2.0.X version?

**Comment by JLNNN** [comment]
Yeah I know. But is there an easy way? In my composer.json is currently only one line with MM:
`"metamodels/bundle_all": "2.0.0"`

`composer update metamodels/bundle_all` is therefore doing nothing as there's no newer release for bundle_all. In the composer.json from bundle_all are two references
```json
  "require": {
    "metamodels/bundle_attributes": "~2.0",
    "metamodels/bundle_filter": "~2.0"
  }
```

Do I have to replace my metamodels/bundle_all with metamodels/bundle_attributes & metamodels/bundle_filter? (These are still outdated bundles, so I have to do the same again? -> check composer.json and include requirements.)

Thanks for guiding me in the right direction.

**Comment by zonky2** [comment]
> Yeah I know. But is there an easy way? In my composer.json is currently only one line with MM:
"metamodels/bundle_all": "2.0.0"

thats correct

run `composer update -v` thats all

you can check `composer show`

btw: your question is for the forum not for issues

**Comment by JLNNN** [comment]
Thank you. Your hint that it can come from another extension/script was right. I used
`grep -rl "String::" /path/to/contao/root`
to find it.
