### ISSUE TITLE
Fehler in MM 2.2.1 nach Update auf Contao 4.4.47

### ISSUE THREAD

**Issue by landzone21** [MetaModels/bundle_all#8]
Nach dem Update von Contao 4.4.46 auf 4.4.47 erhalte ich folgende Fehlermeldung und kann das Installtool nicht mehr aufrufen:
`app.CRITICAL: An exception occurred. {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\ClassNotFoundException(code: 0): Attempted to load class \"AbstractMigration\" from namespace \"Contao\\CoreBundle\\Migration\".\nDid you forget a \"use\" statement for \"ContaoCommunityAlliance\\Polyfills\\Polyfill49\\Migration\\AbstractMigration\"? at /.../vendor/metamodels/attribute_langcode/src/Migration/AllowNullMigration.php:34)"} `

**Comment by discordier** [comment]
See https://github.com/contao-community-alliance/contao-polyfill-bundle/issues/3

**Comment by zonky2** [comment]
@landzone21 MM 2.1 ist nur für Contao 4.4 frei gegeben - siehe Handbuch... MM 2.2 dann wieder für C 4.9

**Comment by landzone21** [comment]
@zonky2 Es geht ja auch um Contao 4.4, gibt es eine Möglichkeit, den Stand vor dem Update wieder herzustellen mittels Contao Manager?

**Comment by zonky2** [comment]
stimmt... habe die "7" zu weit links gesehen :D

der Bug sollte inzwischen gefixt sein - Du kannst die vorherigen Versionen in der composer. json bzw. CM eintragen

**Comment by landzone21** [comment]
@zonky2 Stimmt, Bug ist schon gefixt, vielen Dank, funktioniert alles wieder.
