### ISSUE TITLE
Bug with Input screen backoffice class

### ISSUE THREAD

**Issue by JLBA** [MetaModels/bundle_all#9]
Hello,
I got a fresh Contao 4.9.32 install with Metamodels bundle_all 2.1.1 installed via the Manager.

When in an Input screen backend, I got this error when clicking on DCA little button to select backend class.  
`Return value of Contao\CoreBundle\Translation\Translator::getFromGlobals() must be of the type string or null, array returned`

I got the same error under Contao 4.4 and MM 2.1.1.

Thanks for your help.

**Comment by zonky2** [comment]
Can you make a screenshot and post it here?

**Comment by JLBA** [comment]
Hello,

Of course I can.

When I cilck on the right DCA button, I got :

Le 17/08/2022 à 12:15, zonky2 a écrit :

**Comment by zonky2** [comment]
ahh - i think i know what you mean.... with the icon the popup for selecting the DCA data should open.

The icon and popup no longer exist in MM 2.2 and further, because the popups have always made trouble. Enter your data manually: `filter;search;sort;limit` - or use `,` for inline

**Comment by JLBA** [comment]
Ok. No problem. 

But can you give me the list of backend classes (w50...) as I don't know where to find them ?

**Comment by zonky2** [comment]
look at Contao manual or check the CSS file... it´s only Contao...

**Comment by JLBA** [comment]
Ok.
